### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by jibin2706** [jibin2706/react-calculator#1]
Calculator is not displaying properly in smaller screens.

**Comment by sidalidev** [comment]
I'd love to contribute to this issue 🙂

**Comment by sidalidev** [comment]
@jibin2706 Here you go, let me know if it fits for the needs 🙂

**Comment by jibin2706** [comment]
@sidbentifraouine It isn't working for every device.
The calculator should take the whole screen in smaller screen.

**Comment by sidalidev** [comment]
@jibin2706 M'kay, I'll check this out.

**Comment by sidbentifraouine** [comment]
@jibin2706 M'kay, I'll check this out.

**Comment by sidalidev** [comment]
@jibin2706 I've done some adjustments, you tell me.
