### ISSUE TITLE
Division not proper

### ISSUE THREAD

**Issue by jibin2706** [jibin2706/react-calculator#2]

**Comment by jibin2706** [comment]
Floating point division

**Comment by alizhdanov** [comment]
I'll fix it

But what you mean by not proper? Any examples?

**Comment by jibin2706** [comment]
@alizhdanov like 2/3 
the result goes out of the screen

**Comment by jibin2706** [comment]
In Display component try using input tag instead of div and rounding of the digits after few decimal values

**Comment by celinrayen** [comment]
I can take it. I have a solution ready.

**Comment by celinrayen** [comment]
> @alizhdanov like 2/3
> the result goes out of the screen

Then I think the issue applies for any big number input. like `123456789098765432123456789`. Please update the Issue description with the closest expected result.

Hope you wanted to fix the `Display` to accommodate any big number.
